[package]
name = "windwaker"
version = "0.1.0"
edition = "2021"

[dependencies]
dolphin-memory = "0.2.2"
serde = { version = "1", features = ["derive"] }
bit_field = "0.10.1"

[lib]
name = "windwaker"
path = "src/lib.rs"
